#!/bin/bash
#
# Configure cluster before any operation
#
# Set port to 30000 like minikube
export APISERVER_PORT=30000

# Create only 1 node 
export NUM_NODES=1

# Set coredns as dns
export DNS_SERVICE='coredns'

# Root of persistent data managed by NFS
#
# More info: https://www.digitalocean.com/community/tutorials/how-to-set-up-an-nfs-mount-on-ubuntu-14-04
#
export CLUSTER_PERSISTENT_DATA_FOLDER="$HOME/var/data/k8s"

# Create persisten data folder for default namespace
mkdir -p "$CLUSTER_PERSISTENT_DATA_FOLDER/default"

$(which dind-cluster.sh) $@
